### ISSUE TITLE
f claim error

### ISSUE THREAD

**Issue by DuckCraftPvP** [redstone/LegacyFactions#21] opened 2017-06-19 19:57 UTC
I cant unclaim land in a radius or all ./f unclaimall or /f unclaim 50

https://hastebin.com/tinasexubi.vbs

it looks like it works but it dont, it only unclaims 1 chunk instead of all or 50 chunks.

also i updated my last error that should help fix it ez.

**Comment by DuckCraftPvP** [comment] 2017-06-21 16:34
console says this: https://hastebin.com/yeyodifeve.md :P

**Comment by DuckCraftPvP** [comment] 2017-06-21 16:35
unclaims the same chunk x 50

**Comment by MarkehMe** [comment] 2017-06-22 04:56
Duplicate of #19

**Closed by MarkehMe** 2017-06-22 04:56 UTC

**Comment by DuckCraftPvP** [comment] 2017-06-22 15:24
its not a duplicate, one is /f show and 1 is /f unclaim radius

**Comment by MarkehMe** [comment] 2017-06-22 21:57
They are the same error caused by the same thing. :)

**Comment by DuckCraftPvP** [comment] 2017-06-22 21:58
oh, Well when will it be fixed?
